version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: susti-db
    environment:
      POSTGRES_DB: susti
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - susti-network

  backend:
    image: redox11223/susti-backend:1.0
    container_name: susti-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/susti
      SPRING_DATASOURCE_USERNAME: prueba
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - susti-network

  frontend:
    image: martinplusx/susti-frontend:1.0
    container_name: susti-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://localhost:8080
    networks:
      - susti-network

volumes:
  postgres-data:

networks:
  susti-network:
    driver: bridge
